"""empty message

Revision ID: 31147d42254e
Revises: 45eb8dbc9d9e
Create Date: 2017-07-20 16:00:26.669000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31147d42254e'
down_revision = '45eb8dbc9d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
